name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v4 

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Test collector
      run: python3 collector_analyser/flask_collector_test.py
    - name: Test analyser
      run: python3 collector_analyser/flask_analyser_test_mock.py
    - name: Test dynamodb_util
      run: python3 collector_analyser/dynamodb_util_test.py
    # - name: Test sqs_util
    #   env:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    #   run: python3 collector_analyser/sqs_util_test.py

    - name: Copy Code files to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        SSH_OPTIONS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa"
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa collector_analyser/*.py ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./requirements.txt ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/ 
        
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}

    - name: Run Analyser on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'cd /home/ubuntu && python3 flask_analyser.py'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
